### ISSUE TITLE
using rustc 1.35.0

### ISSUE THREAD

**Issue by hiqbn** [seppo0010/rsedis#10]
cant run cargo build

warning: unused import: libc::funcs::c95::ctype::isprint

compiling parser v0.1.0 ...... rsedis/parser
error[E0554].....
skiplist.0.2.10/src/lib.rs:26:35

**Comment by seppo0010** [comment]
You should be using rust nightly.

**Comment by hiqbn** [comment]
it's great piece of software. however, possible for you to do a simple stable rust version of 
https://github.com/tidwall/redcon ?

it'll be of great use to many developers as a redis tcp protocol connector.

**Comment by seppo0010** [comment]
I am not putting any effort in this, it was just a learning experiment for me. I don't think it is that great to be honest, it might be better to start from scratch unfortunately.

**Comment by hiqbn** [comment]
would you consider a donation / being paid for this? just conversion to simple redis protocol 
https://github.com/tidwall/redcon
like that will do.

**Comment by seppo0010** [comment]
I would not. Thank you.
