### ISSUE TITLE
What's the plan?

### ISSUE THREAD

**Issue by longwusha** [seppo0010/rsedis#12]
As we can see, your last commit was almost 3 years ago. So, what's the plan?

Are you still working on this?

**Comment by longwusha** [comment]
In these 3 years, both redis and rust have changed a lot.

**Comment by seppo0010** [comment]
I am not.

**Comment by seppo0010** [comment]
If you want to make something like this, I would suggest to start from scratch. There are many unaddressed issues that require consideration from the beginning (for example, how to handle parallelization if wanted), many things that can be done in a more rust-y way (using nom, failure, serde, env_logger) and other things that can be done more efficiently (for example not returning a Response object but instead receiving a write-like object to write the response, avoiding unnecessary memory copy).

I think it was a fun learning experiment for me, but I don't think it is useful in any way.
