### ISSUE TITLE
Can not compile on windows

### ISSUE THREAD

**Issue by fedorkotov** [seppo0010/rsedis#15]
Can not compile on windows for x86_64-pc-windows-msvc target with VisualStudio 2019.

```
... almost 50k lines ommited ...
error: aborting due to 4550 previous errors

For more information about this error, try `rustc --explain E0412`.
error: Could not compile `kernel32-sys`.
```
(see full cargo output [build.log.msvc.txt](https://github.com/seppo0010/rsedis/files/3498299/build.log.msvc.txt))

[kernel32-sys crate is now obsolete](https://github.com/retep998/winapi-rs#should-i-still-use-those--sys-crates-such-as-kernel32-sys) and should be replaced with winapi.

**Comment by seppo0010** [comment]
Thanks!
