### ISSUE TITLE
How did you do the implementation?

### ISSUE THREAD

**Issue by GeertVL** [seppo0010/rsedis#2]
I am always curious on how people do the "conversion" from one language to another?
Did you take the original source code and translated it one file after another or did you take the concepts and try to implement it or another way?

Sorry for my curious mind. Thanks.

**Comment by seppo0010** [comment]
I took the Redis commands and configuration, stored as a [todo list](https://github.com/seppo0010/rsedis/blob/master/TODO.md) and implemented how I felt it was the Rust way. I only did literal translation for small pieces of code, like configuration parsing.
