### ISSUE TITLE
Project restructure 

### ISSUE THREAD

**Issue by gkorland** [seppo0010/rsedis#24]
1. Move to workspaces - https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
2. edition = "2021"

**Comment by seppo0010** [comment]
I'm not actively supporting this project. Sorry.

**Comment by gaojunran** [comment]
Do you still accept pr now? I want to make contributions for this project!

**Comment by seppo0010** [comment]
I do not. Fork it and continue on your own if you want.
